### ISSUE TITLE
Color Constants:  CELESTE

### ISSUE THREAD

**Issue by natebean** [fletchto99/PHPebbleTimeline#1]
Great work.  Thanks for sharing!!!

Using the color constants.

CELESTE = '#AAFFF';
is missing an F
Should be 
CELESTE = '#AAFFFF';

**Comment by fletchto99** [comment]
I'll be sure to get that fixed up tomorrow! Good catch thanks!

**Comment by natebean** [comment]
Sounds good, thanks!

**Comment by fletchto99** [comment]
Fixed in commit 71672fcfa59a7b8ab712e5f888180b7974310af3
