### ISSUE TITLE
Pin Actions won't Create Pins

### ISSUE THREAD

**Issue by getmethere** [fletchto99/PHPebbleTimeline#3]
This will work:
<img width="655" alt="screen shot 2015-12-08 at 1 56 33 pm" src="https://cloud.githubusercontent.com/assets/11246733/11665283/939d9082-9db4-11e5-989e-2a52868b7001.png">

This will report success, but will not create the pin:
<img width="646" alt="screen shot 2015-12-08 at 1 57 52 pm" src="https://cloud.githubusercontent.com/assets/11246733/11665298/9f15f332-9db4-11e5-8689-490de6ddd831.png">

**Comment by fletchto99** [comment]
Taking a look at your code it appears on line 22 in you example where the pin fails to send you have `OPEN_WATCH_APP` instead this should be `PinActionType::OPEN_WATCH_APP`
